# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HMAMapView' do
    pod 'AMap3DMap-NO-IDFA'
    pod 'AMapFoundation-NO-IDFA'

    pod 'Masonry'
end
